language: ruby
rvm:
  - 2.2.1

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - zabelin.alex@gmail.com
    on_failure: change
    on_success: never

after_success:
  - CI=true TRAVIS=true coveralls --verbose
